# config_experiments.yaml
# 複数モデルの自動検証用設定ファイル

# --- 全実験で共通の設定 ---
training_data_dir: "training_data"
sequence_length: 30
overlap_ratio: 0.5
sample_ratio: 1.0 # 1.0で全データ使用

# --- 学習に関する共通設定 ---
learning_rate: 0.001
epochs: 150
patience: 25

# --- 交差検証に関する共通設定 ---
n_splits: 5
execution_mode: 'full' # 'full' または 'cv_only'

# --- CPU実行時の共通オーバーライド設定 ---
cpu_settings:
  sequence_length: 20
  batch_size: 32
  epochs: 100
  patience: 15
  # 注意：以下のlstm_unitsは実験ごとに上書きされます
  lstm_units: [64]

# -----------------------------------------------------------------------------
# --- ▼ ここから下に、試したいモデルの組み合わせをリストで記述します ▼ ---
# -----------------------------------------------------------------------------
model_experiments:
  # # --- 実験1: ベースライン (Stacked LSTM) ---
  # - name: "1_Baseline_Stacked"
  #   model_type: "stacked"
  #   sequence_length: 30
  #   lstm_units: [128, 64]      # hidden_sizes: -> lstm_units: に修正
  #   dropout_rate: 0.4
  #   learning_rate: 0.001
  #   batch_size: 128
  #   enable_confidence_weighting: false

  # # --- 実験2: 双方向モデル (Bidirectional) ---
  # - name: "2_Bidirectional"
  #   model_type: "bidirectional"
  #   sequence_length: 30
  #   lstm_units: [128, 64]      # hidden_sizes: -> lstm_units: に修正
  #   dropout_rate: 0.5
  #   learning_rate: 0.001
  #   batch_size: 128
  #   enable_confidence_weighting: false

  # # --- 実験3: シンプルモデル (Simple) ---
  # - name: "3_Simple"
  #   model_type: "simple"
  #   sequence_length: 30
  #   lstm_units: [128]          # hidden_sizes: -> lstm_units: に修正
  #   dropout_rate: 0.4
  #   learning_rate: 0.001
  #   batch_size: 128
  #   enable_confidence_weighting: false

  # # --- 実験4: 信頼度重み付けの効果 ---
  # - name: "4_With_Confidence"
  #   model_type: "stacked"
  #   sequence_length: 30
  #   lstm_units: [128, 64]      # hidden_sizes: -> lstm_units: に修正
  #   dropout_rate: 0.4
  #   learning_rate: 0.001
  #   batch_size: 128
  #   enable_confidence_weighting: true

  # # --- 実験5: より深いStackedモデル ---
  # - name: "5_Deeper_Stacked"
  #   model_type: "stacked"
  #   sequence_length: 30
  #   lstm_units: [256, 128, 64] # hidden_sizes: -> lstm_units: に修正
  #   dropout_rate: 0.5
  #   learning_rate: 0.001
  #   batch_size: 128
  #   enable_confidence_weighting: false

  # --- 実験6: 長いシーケンス + 双方向 ---
  - name: "6_LongSeq_Bidirectional"
    model_type: "bidirectional"
    sequence_length: 45
    lstm_units: [128, 64]      # hidden_sizes: -> lstm_units: に修正
    dropout_rate: 0.5
    learning_rate: 0.001
    batch_size: 64
    enable_confidence_weighting: false

  # # --- 実験7: 短いシーケンス ---
  # - name: "7_ShortSeq_Stacked"
  #   model_type: "stacked"
  #   sequence_length: 15
  #   lstm_units: [128, 64]      # hidden_sizes: -> lstm_units: に修正
  #   dropout_rate: 0.4
  #   learning_rate: 0.001
  #   batch_size: 128
  #   enable_confidence_weighting: false